services:
  nginx:
    image: nginx:alpine
    container_name: rd_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orders
      - frontend
  db:
    image: postgres:16
    container_name: rd_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrations:
    image: golang:1.25
    container_name: rd_migrations
    volumes:
      - ./backend/migrations:/migrations
      # - ./.env:/app/.env
    working_dir: /migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: "${DB_DSN}"
    command: >
      sh -c "
        go install github.com/pressly/goose/v3/cmd/goose@latest &&
        goose -dir /migrations postgres \"$$DB_DSN\" up
      "
  goose-shell:
    image: golang:1.25
    container_name: rd_goose_shell
    volumes:
      - ./backend/migrations:/migrations
      # - ./.env:/app/.env
    working_dir: /migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_DSN=${DB_DSN:-postgres://root:root@db:5432/rovno_dev?sslmode=disable}
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      echo 'Installing goose...' &&
      go install github.com/pressly/goose/v3/cmd/goose@latest &&
      echo 'Goose installed.' &&
      echo 'Database: $$DB_DSN' &&
      echo '' &&
      echo 'Available commands:' &&
      echo '  goose status' &&
      echo '  goose up' &&
      echo '  goose down' &&
      echo '  goose create <name> sql' &&
      echo '' &&
      /bin/bash
      "
  frontend:
    container_name: rd_frontend
    build:
      context: ./frontend
      target: ${FRONTEND_TARGET}
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
  orders:
    container_name: rd_orders
    build:
      context: ./backend/services/orders
      target: ${ORDERS_TARGET:-prod}
    working_dir: /app
    volumes:
      - ./backend/services/orders:/app
    depends_on:
      - db
      - migrations
    environment:
      DB_DRIVER: "${DB_DRIVER}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: ${DB_PORT}
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_SSLMODE: "${DB_SSLMODE}"
    ports:
      - "${ORDERS_PORT}:${APP_PORT}"
    # profiles:
    #   - dev
    #   - prod
volumes:
  db_data:
