services:
  orders:
    build:
      target: dev
    volumes:
      - ./backend/services/orders:/app
  nginx-dev:
    profiles: ["dev"]
    image: nginx:alpine
    container_name: rd_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orders
