services:
  db:
    image: postgres:16
    container_name: rd_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: golang:1.25
    container_name: rd_migrations
    volumes:
      - ./backend/migrations:/migrations
    working_dir: /migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DSN: "${DB_DSN}"
    command: >
      sh -c "go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir /migrations postgres \"$$DB_DSN\" up"

  orders:
    container_name: rd_orders
    build:
      context: ./backend/services/orders
      target: prod
    working_dir: /app
    depends_on:
      - db
      - migrations
    environment:
      GIN_MODE: "${GIN_MODE}"
      DB_DRIVER: "${DB_DRIVER}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: ${DB_PORT}
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_SSLMODE: "${DB_SSLMODE}"
    ports:
      - "${ORDERS_PORT}:${DEFAULT_PORT}"

  frontend:
    container_name: rd_frontend
    profiles: ["prod"]
    build:
      context: ./frontend
      target: prod
    working_dir: /app
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}

  nginx:
    profiles: ["prod"]
    image: nginx:alpine
    container_name: rd_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orders
      - frontend
  goose-shell:
    image: golang:1.25
    container_name: rd_goose_shell
    volumes:
      - ./backend/migrations:/migrations
    working_dir: /migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_DSN=${DB_DSN}
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]

volumes:
  db_data:
